const $=id=>document.getElementById(id), money=n=>`₺${Number(n).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})}`, num=n=>Number(n).toLocaleString('tr-TR',{minimumFractionDigits:1,maximumFractionDigits:1});
let current=null, installPrompt=null;

$('search').addEventListener('submit',async event=>{event.preventDefault();await run($('symbol').value)});
$('favorite').addEventListener('click',toggleFavorite);
$('scan').addEventListener('click',scanMarket);
$('portfolioForm').addEventListener('submit',saveHolding);
$('refreshPortfolio').addEventListener('click',refreshPortfolio);
$('homeNav').addEventListener('click',clearScanView);
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('install').hidden=false});
$('install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('install').hidden=true}else alert("Safari'de Paylaş düğmesine, ardından ‘Ana Ekrana Ekle’ye dokunun.")});

async function run(raw){const symbol=raw.trim().toUpperCase().replace('.IS','');$('symbol').value=symbol;$('error').hidden=true;$('result').hidden=true;$('loader').hidden=false;try{const response=await fetch(`/api/history?symbol=${encodeURIComponent(symbol)}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'Veri alınamadı.');current=analyze(data);render(current);$('result').hidden=false;$('result').scrollIntoView({behavior:'smooth'})}catch(error){$('error').textContent=error.message;$('error').hidden=false}finally{$('loader').hidden=true}}

function analyze(data){const rows=data.rows;if(rows.length<200)throw new Error('Analiz için en az 200 günlük veri gerekiyor.');const closes=rows.map(x=>x.c), highs=rows.map(x=>x.h), lows=rows.map(x=>x.l), volumes=rows.map(x=>x.v||0);const last=closes.at(-1), prev=closes.at(-2), e20=ema(closes,20).at(-1),e50=ema(closes,50).at(-1),e200=ema(closes,200).at(-1);const r=rsi(closes,14),macdLine=ema(closes,12).map((x,i)=>x-ema(closes,26)[i]),signal=ema(macdLine,9).at(-1),m=macdLine.at(-1),a=atr(rows,14);const vAvg=avg(volumes.slice(-20)),vRatio=vAvg?volumes.at(-1)/vAvg:1;let score=0,pos=[],neg=[];
  if(last>e20){score+=15;pos.push('Fiyat EMA20 üzerinde.')}else neg.push('Fiyat kısa vadeli EMA20 altında.');if(e20>e50){score+=20;pos.push('EMA20, EMA50 üzerinde; kısa trend olumlu.')}else neg.push('EMA20, EMA50 altında; trend teyidi zayıf.');if(last>e200){score+=15;pos.push('Fiyat uzun vadeli EMA200 üzerinde.')}else neg.push('Fiyat EMA200 altında.');if(r>=45&&r<=65){score+=20;pos.push(`RSI ${num(r)} ile dengeli bölgede.`)}else if(r>=70)neg.push(`RSI ${num(r)}; aşırı alım riski var.`);else if(r<40)neg.push(`RSI ${num(r)}; momentum zayıf.`);if(m>signal){score+=20;pos.push('MACD, sinyal çizgisinin üzerinde.')}else neg.push('MACD pozitif teyit vermiyor.');if(vRatio>1.2){score+=10;pos.push('Hacim son 20 gün ortalamasının üzerinde.')}else if(vRatio<.8)neg.push('Hacim hareketi yeterince desteklemiyor.');
  const support=Math.min(...lows.slice(-20)),resistance=Math.max(...highs.slice(-60));const stop=Math.min(last*.985,Math.max(last-a*1.5,support*.98));const target=Math.max(last+a*2,resistance>last?resistance:last*1.06);const buyLow=Math.max(.01,Math.min(last*.98,e20)),buyHigh=last*1.01,rr=(target-last)/Math.max(last-stop,.01);if(rr<1.5)neg.push(`Risk/getiri 1:${num(rr)} ile 1:1,5 eşiğinin altında.`);score=Math.max(0,Math.min(100,score));const stale=businessAge(rows.at(-1).t),confidence=Math.max(0,Math.min(90,90-stale*10));if(stale>1)neg.unshift(`Veri ${stale} işlem günü eski; karar güncel fiyatla doğrulanmalı.`);const decision=stale>2?'VERİYİ KONTROL ET':score>=75&&rr>=1.5?'ALIM İÇİN İZLE':score>=50?'BEKLE / TAKİP ET':'YENİ ALIM YAPMA';return{symbol:data.symbol,last,prev,r,e20,e50,score,confidence,stale,date:new Date(rows.at(-1).t*1000),buyLow,buyHigh,target,stop,rr,pos:pos.length?pos:['Belirgin olumlu ortak teyit bulunamadı.'],neg:neg.length?neg:['Belirgin ek risk alarmı oluşmadı.'],decision,trend:e20>e50?'POZİTİF':'ZAYIF'};}

function render(x){$('date').textContent=`${x.symbol} · ${x.date.toLocaleDateString('tr-TR')}`;$('decision').textContent=x.decision;$('decisionText').textContent=x.score>=75?'Teknik göstergeler ortak teyit veriyor; seviyeleri ve güncel veriyi kontrol edin.':'Göstergeler henüz güçlü ve ortak bir alım teyidi vermiyor.';$('score').textContent=`${x.score}/100`;$('price').textContent=money(x.last);const change=(x.last/x.prev-1)*100;$('change').textContent=`${change>=0?'+':''}%${num(change)}`;$('change').className=change>=0?'up':'down';$('rsi').textContent=num(x.r);$('rsiText').textContent=x.r>=70?'Aşırı alım':x.r<40?'Zayıf':'Dengeli';$('trend').textContent=x.trend;$('confidence').textContent=`%${x.confidence}`;$('dataAge').textContent=x.stale?'Gecikmeli veri':'Son işlem günü';$('buy').textContent=`${money(x.buyLow)} – ${money(x.buyHigh)}`;$('target').textContent=money(x.target);$('stop').textContent=money(x.stop);$('rr').textContent=`1:${num(x.rr)}`;fill('positive',x.pos);fill('negative',x.neg);updateFavorite()}
function fill(id,values){const el=$(id);el.replaceChildren(...values.map(value=>{const li=document.createElement('li');li.textContent=value;return li}))}
function ema(values,period){const k=2/(period+1),out=[values[0]];for(let i=1;i<values.length;i++)out.push(values[i]*k+out[i-1]*(1-k));return out}
function rsi(values,period){let gains=0,losses=0;for(let i=values.length-period;i<values.length;i++){const d=values[i]-values[i-1];if(d>0)gains+=d;else losses-=d}if(!losses)return 100;return 100-(100/(1+(gains/period)/(losses/period)))}
function atr(rows,period){const tr=[];for(let i=1;i<rows.length;i++)tr.push(Math.max(rows[i].h-rows[i].l,Math.abs(rows[i].h-rows[i-1].c),Math.abs(rows[i].l-rows[i-1].c)));return avg(tr.slice(-period))}
function avg(a){return a.reduce((s,x)=>s+x,0)/Math.max(a.length,1)}
function businessAge(timestamp){let d=new Date(timestamp*1000),now=new Date(),n=0;d.setHours(12,0,0,0);now.setHours(12,0,0,0);while(d<now){d.setDate(d.getDate()+1);if(d.getDay()!==0&&d.getDay()!==6)n++}return Math.max(0,n-1)}
function saved(){try{return JSON.parse(localStorage.getItem('borsa-watch')||'[]')}catch{return[]}}
function toggleFavorite(){if(!current)return;let list=saved(),s=current.symbol;list=list.includes(s)?list.filter(x=>x!==s):[...list,s].slice(-20);localStorage.setItem('borsa-watch',JSON.stringify(list));updateFavorite();renderWatch()}
function updateFavorite(){if(!current)return;$('favorite').textContent=saved().includes(current.symbol)?'★ Takip listesinden çıkar':'☆ Takip listeme ekle'}
function renderWatch(){const list=saved(),el=$('watchlist');if(!list.length){el.innerHTML='<span class="empty">Henüz hisse eklenmedi.</span>';return}el.replaceChildren(...list.map(s=>{const b=document.createElement('button');b.className='chip';b.textContent=s;b.onclick=()=>run(s);return b}))}renderWatch();
async function scanMarket(){const button=$('scan'),progress=$('scanProgress'),error=$('scanError'),results=$('scanResults');button.disabled=true;button.textContent='Tarama sürüyor…';progress.hidden=false;error.hidden=true;results.replaceChildren();let offset=0,total=120,all=[];try{while(offset<total){const response=await fetch(`/api/scan?offset=${offset}&limit=4`);const data=await response.json();if(!response.ok)throw new Error(data.error||'Tarama verisi alınamadı.');all.push(...data.candidates);offset=data.next;total=data.total;const pct=Math.round(offset/total*100);$('progressBar').style.width=`${pct}%`;$('progressText').textContent=`${offset} / ${total} hisse incelendi · ${all.length} aday koşulları geçti`;}all.sort((a,b)=>b.score-a.score||b.rr-a.rr);renderCandidates(all.slice(0,30));$('progressText').textContent=`Tarama tamamlandı · ${all.length} uygun aday bulundu`;localStorage.setItem('last-scan',JSON.stringify({at:Date.now(),items:all.slice(0,30)}))}catch(e){error.textContent=`Tarama durdu: ${e.message}. Tekrar deneyebilirsiniz.`;error.hidden=false}finally{button.disabled=false;button.textContent='Taramayı yenile'}}
function renderCandidates(items){const el=$('scanResults');if(!items.length){el.innerHTML='<span class="empty">Kalite koşullarını geçen aday bulunamadı.</span>';return}el.replaceChildren(...items.map((x,index)=>{const row=document.createElement('article');row.className='candidate';row.innerHTML=`<span class="rank">#${index+1}</span><div><b>${x.symbol} · ${money(x.price)}</b><small>${x.status} · Hedef ${money(x.target)} · Stop ${money(x.stop)}</small></div><div class="candidate-score">${x.score}<small>PUAN</small></div>`;row.onclick=()=>run(x.symbol);return row}))}
try{const cached=JSON.parse(localStorage.getItem('last-scan')||'null');if(cached?.items?.length&&Date.now()-cached.at<6*60*60*1000){renderCandidates(cached.items);$('progressText').textContent='Son tarama sonucu gösteriliyor';$('scanProgress').hidden=false;$('progressBar').style.width='100%'}}catch{}
function holdings(){try{return JSON.parse(localStorage.getItem('borsa-portfolio')||'[]')}catch{return[]}}
function parseTr(value){const text=String(value||'').trim().replace(/\s/g,'');const normalized=text.includes(',')?text.replace(/\./g,'').replace(',','.'):text;return Number(normalized)}
function saveHolding(event){event.preventDefault();const symbol=$('portfolioSymbol').value.trim().toUpperCase().replace('.IS',''),quantity=parseTr($('portfolioQuantity').value),buyPrice=parseTr($('portfolioBuyPrice').value),error=$('portfolioError');error.hidden=true;if(!/^[A-Z0-9_]{3,6}$/.test(symbol)||!(quantity>0)||!(buyPrice>0)){error.textContent='Geçerli bir hisse kodu, adet ve alış fiyatı girin.';error.hidden=false;return}let items=holdings();const old=items.find(x=>x.symbol===symbol);const item={symbol,quantity,buyPrice,last:old?.last||null,updated:old?.updated||null};items=old?items.map(x=>x.symbol===symbol?item:x):[...items,item];localStorage.setItem('borsa-portfolio',JSON.stringify(items));event.target.reset();renderPortfolio();refreshHolding(symbol)}
async function fetchLast(symbol){const response=await fetch(`/api/quote?symbol=${encodeURIComponent(symbol)}`),data=await response.json();if(!response.ok)throw new Error(data.error||'Fiyat alınamadı');return{price:data.price,timestamp:data.timestamp}}
async function refreshHolding(symbol){setPortfolioBusy(true);try{const quote=await fetchLast(symbol);const items=holdings().map(x=>x.symbol===symbol?{...x,last:quote.price,priceTime:quote.timestamp,updated:Date.now()}:x);localStorage.setItem('borsa-portfolio',JSON.stringify(items));renderPortfolio()}catch(e){$('portfolioError').textContent=`${symbol}: ${e.message}`;$('portfolioError').hidden=false}finally{setPortfolioBusy(false)}}
async function refreshPortfolio(){const items=holdings();if(!items.length)return;setPortfolioBusy(true);$('portfolioError').hidden=true;let failures=[];for(const item of items){try{const quote=await fetchLast(item.symbol);const current=holdings().map(x=>x.symbol===item.symbol?{...x,last:quote.price,priceTime:quote.timestamp,updated:Date.now()}:x);localStorage.setItem('borsa-portfolio',JSON.stringify(current));renderPortfolio()}catch(e){failures.push(item.symbol)}}if(failures.length){$('portfolioError').textContent=`Fiyatı alınamayanlar: ${failures.join(', ')}`;$('portfolioError').hidden=false}setPortfolioBusy(false)}
function setPortfolioBusy(busy){$('refreshPortfolio').disabled=busy;$('refreshPortfolio').textContent=busy?'Fiyatlar güncelleniyor…':'Portföy fiyatlarını güncelle'}
function removeHolding(symbol){localStorage.setItem('borsa-portfolio',JSON.stringify(holdings().filter(x=>x.symbol!==symbol)));renderPortfolio()}
function renderPortfolio(){const items=holdings(),list=$('portfolioList'),summary=$('portfolioSummary');if(!items.length){list.innerHTML='<span class="empty">Henüz portföy kaydı eklenmedi.</span>';summary.hidden=true;return}let cost=0,value=0,valuedCost=0;list.replaceChildren(...items.map(item=>{const itemCost=item.quantity*item.buyPrice,current=Number.isFinite(item.last)?item.quantity*item.last:null,profit=current===null?null:current-itemCost,pct=profit===null?null:profit/itemCost*100;cost+=itemCost;if(current!==null){value+=current;valuedCost+=itemCost}const priceDate=item.priceTime?new Date(item.priceTime*1000).toLocaleString('tr-TR',{dateStyle:'short',timeStyle:'short'}):'Fiyatı yeniden güncelleyin';const row=document.createElement('article');row.className='holding';row.innerHTML=`<div class="holding-head"><strong>${item.symbol}</strong><small>${item.quantity.toLocaleString('tr-TR')} ADET</small></div><div class="holding-grid"><p><small>ALIŞ</small><b>${money(item.buyPrice)}</b></p><p><small>SON FİYAT</small><b>${Number.isFinite(item.last)?money(item.last):'—'}</b><small>${priceDate}</small></p><p><small>MALİYET</small><b>${money(itemCost)}</b></p><p><small>DEĞER</small><b>${current===null?'—':money(current)}</b></p></div><div class="holding-actions"><span class="${profit===null?'':profit>=0?'up':'down'}">${profit===null?'Fiyatı güncelleyin':`${profit>=0?'+':''}${money(profit)} · %${num(pct)}`}</span><button type="button">Kaydı sil</button></div>`;row.querySelector('button').onclick=()=>removeHolding(item.symbol);return row}));const complete=items.every(x=>Number.isFinite(x.last)&&x.priceTime);$('totalCost').textContent=money(cost);$('currentValue').textContent=complete?money(value):'Fiyatları güncelleyin';const total=value-valuedCost;$('totalProfit').textContent=complete?`${total>=0?'+':''}${money(total)} · %${num(total/valuedCost*100)}`:'—';$('totalProfit').className=complete?(total>=0?'up':'down'):'';summary.hidden=false}
renderPortfolio();
function clearScanView(){$('scanResults').replaceChildren();$('scanProgress').hidden=true;$('scanError').hidden=true;$('progressBar').style.width='0';$('progressText').textContent='';localStorage.removeItem('last-scan')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
